[package]
name = "rust-rocket-app"
version = "0.1.0"
authors = ["kramachandra <karthick.ramachandran@zalando.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
